### ISSUE TITLE
bad

### ISSUE THREAD

**Issue by bepri** [ObKnoxious/COSC302#1]
code sucks. not enough comments. your `ifstream` object shouldve just been named `f`, `fin` is too many extra letters

**Comment by ObKnoxious** [comment]
fin has been replaced with F in [latest commit](https://github.com/ObKnoxious/COSC302/commit/b98dd0bbda7aeeb0b53720148e24a3002acc04f3). Additional comment documentation was also added at the end of Fruit2.cpp
